
Currently Loaded Modules:
  1) tools/miniconda/python3.8/4.9.2

 

WARNING: overwriting environment variables set in the machine
overwriting variable nnUNet_raw_data_base nnUNet_preprocessed RESULTS_FOLDER OUTPUT
  Running command git clone -q https://github.com/FabianIsensee/hiddenlayer.git /tmp/pip-install-8tm7wlci/hiddenlayer_5caaa41c89ae49ea9365528063244db9
  Running command git checkout -b more_plotted_details --track origin/more_plotted_details
  Switched to a new branch 'more_plotted_details'
  Branch 'more_plotted_details' set up to track remote branch 'more_plotted_details' from 'origin'.
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/smaijer/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/home/smaijer/nnUNet/nnunet/preprocessing/sanity_checks.py", line 131, in verify_dataset_integrity
    assert all([isfile(i) for i in
AssertionError: some image files are missing for case panc_0001. Expected files:
 ['/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task700/imagesTr/panc_0001_0000.nii.gz', '/exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task700/imagesTr/panc_0001_0001.nii.gz']
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/smaijer/nnUNet/nnunet/run/run_training.py", line 138, in main
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/smaijer/nnUNet/nnunet/run/default_configuration.py", line 47, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/smaijer/.conda/envs/nn/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/exports/lkeb-hpc/smaijer/data/nnUNet_preprocessed/Task700/nnUNetPlansv2.1_plans_3D.pkl'
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 56, in main
    consolidate_folds(folder, val)
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 61, in consolidate_folds
    collect_cv_niftis(output_folder_base, output_folder_raw, validation_folder_name,
  File "/home/smaijer/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 31, in collect_cv_niftis
    raise RuntimeError("some folds are missing. Please run the full 5-fold cross-validation. "
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [0, 1, 2, 3, 4]
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/nnUNet/nnunet/inference/predict_simple.py", line 215, in main
    assert isdir(model_folder_name), "model output folder not found. Expected: %s" % model_folder_name
AssertionError: model output folder not found. Expected: /exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task700/nnUNetTrainerV2__nnUNetPlansv2.1
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/smaijer/nnUNet/nnunet/inference/predict_simple.py", line 215, in main
    assert isdir(model_folder_name), "model output folder not found. Expected: %s" % model_folder_name
AssertionError: model output folder not found. Expected: /exports/lkeb-hpc/smaijer/results/nnUNet/3d_fullres/Task700/nnUNetTrainerV2__nnUNetPlansv2.1
Traceback (most recent call last):
  File "/home/smaijer/.conda/envs/nn/bin/nnUNet_evaluate_folder", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_evaluate_folder')())
  File "/home/smaijer/nnUNet/nnunet/evaluation/evaluator.py", line 483, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/home/smaijer/nnUNet/nnunet/evaluation/evaluator.py", line 456, in evaluate_folder
    assert all([i in files_pred for i in files_gt]), "files missing in folder_with_predictions"
AssertionError: files missing in folder_with_predictions
OrderedDict([('all', []), ('mean', OrderedDict())])
